Task 3: Hierarchical Clustering

In [1]:
# importing necessary libraries
import os
import numpy as np
import pandas as pd
import matplotlib as plt 
from scipy.cluster.hierarchy import dendrogram, linkage

In [2]:
# Loading datasets
filename = os.path.join(os.getcwd(), "prices_pct_float.csv")
filename_2 = os.path.join(os.getcwd(),"volume_float.csv")


In [3]:
# Saving it to a Pandas dataframe
df_prices_pct = pd.read_csv(filename)
df_volume = pd.read_csv(filename_2)


In [4]:
print(df_prices_pct)

    Unnamed: 0         A       AAL      AAPL      ABBV      ABNB       ABT  \
0            0 -0.004186 -0.002602  0.001649  0.012173  0.005675  0.005444   
1            1  0.020711  0.010435  0.007821  0.020353 -0.008839 -0.001934   
2            2 -0.005541 -0.016351 -0.007097  0.018919  0.008369  0.010075   
3            3  0.001205  0.006124  0.012392  0.005042 -0.002313  0.031745   
4            4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
..         ...       ...       ...       ...       ...       ...       ...   
85          85 -0.000284 -0.001967 -0.006753 -0.002654  0.006767 -0.001768   
86          86  0.010421  0.023645  0.014570 -0.001126 -0.007913 -0.001240   
87          87  0.002736  0.022137 -0.003438  0.005790  0.006089  0.004523   
88          88  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
89          89  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

        ACGL       ACN      ADBE  ...       WTW        WY      

In [5]:
print(df_prices_pct.columns)

Index(['Unnamed: 0', 'A', 'AAL', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN',
       'ADBE',
       ...
       'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZTS'],
      dtype='object', length=502)


In [6]:
print(df_prices_pct.dtypes)

Unnamed: 0      int64
A             float64
AAL           float64
AAPL          float64
ABBV          float64
               ...   
XYL           float64
YUM           float64
ZBH           float64
ZBRA          float64
ZTS           float64
Length: 502, dtype: object


In [7]:
df_prices_pct['Unnamed: 0'] = pd.to_numeric(df_prices_pct['Unnamed: 0'], errors='coerce')

In [8]:
df_prices_pct['Unnamed: 0'] = df_prices_pct['Unnamed: 0'].astype(float)

In [9]:
print(df_prices_pct.dtypes)

Unnamed: 0    float64
A             float64
AAL           float64
AAPL          float64
ABBV          float64
               ...   
XYL           float64
YUM           float64
ZBH           float64
ZBRA          float64
ZTS           float64
Length: 502, dtype: object


In [10]:
print(df_prices_pct['Unnamed: 0'].unique())

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.]


In [11]:
print(df_prices_pct['Unnamed: 0'].isna().sum())

0


In [12]:
print(df_prices_pct.head())
print(df_prices_pct.info())

   Unnamed: 0         A       AAL      AAPL      ABBV      ABNB       ABT  \
0         0.0 -0.004186 -0.002602  0.001649  0.012173  0.005675  0.005444   
1         1.0  0.020711  0.010435  0.007821  0.020353 -0.008839 -0.001934   
2         2.0 -0.005541 -0.016351 -0.007097  0.018919  0.008369  0.010075   
3         3.0  0.001205  0.006124  0.012392  0.005042 -0.002313  0.031745   
4         4.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       ACGL       ACN      ADBE  ...       WTW        WY      WYNN       XEL  \
0 -0.008260  0.022359  0.021297  ...  0.000549 -0.008078 -0.020967  0.013567   
1 -0.011699  0.010276  0.016571  ... -0.006152 -0.000679  0.004735 -0.015527   
2  0.004013  0.002474  0.005112  ...  0.003588  0.010526 -0.009426 -0.006164   
3  0.004896 -0.011449  0.015934  ...  0.003811 -0.013441  0.007137 -0.001459   
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

        XOM       XYL       YUM       ZBH      ZBRA     

In [13]:
df_prices_pct.dtypes

Unnamed: 0    float64
A             float64
AAL           float64
AAPL          float64
ABBV          float64
               ...   
XYL           float64
YUM           float64
ZBH           float64
ZBRA          float64
ZTS           float64
Length: 502, dtype: object

In [14]:
print(df_prices_pct['Unnamed: 0'].dtype)

float64


In [15]:
print(df_volume.columns)

Index(['Unnamed: 0', 'A', 'AAL', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACGL', 'ACN',
       'ADBE',
       ...
       'WTW', 'WY', 'WYNN', 'XEL', 'XOM', 'XYL', 'YUM', 'ZBH', 'ZBRA', 'ZTS'],
      dtype='object', length=502)


In [16]:
print(df_volume.dtypes)

Unnamed: 0      int64
A             float64
AAL           float64
AAPL          float64
ABBV          float64
               ...   
XYL           float64
YUM           float64
ZBH           float64
ZBRA          float64
ZTS           float64
Length: 502, dtype: object


In [17]:
df_volume['Unnamed: 0']

0      0
1      1
2      2
3      3
4      4
      ..
58    58
59    59
60    60
61    61
62    62
Name: Unnamed: 0, Length: 63, dtype: int64

In [18]:
df_volume['Unnamed: 0']=df_volume['Unnamed: 0'].astype(float)

In [19]:
df_volume['Unnamed: 0']

0      0.0
1      1.0
2      2.0
3      3.0
4      4.0
      ... 
58    58.0
59    59.0
60    60.0
61    61.0
62    62.0
Name: Unnamed: 0, Length: 63, dtype: float64

In [20]:
print(df_volume['Unnamed: 0'].dtype)

float64


In [21]:
df_volume.dtypes

Unnamed: 0    float64
A             float64
AAL           float64
AAPL          float64
ABBV          float64
               ...   
XYL           float64
YUM           float64
ZBH           float64
ZBRA          float64
ZTS           float64
Length: 502, dtype: object

In [22]:
df_prices_pct = df_prices_pct.drop('Unnamed: 0', axis=1)


In [23]:
df_prices_pct.head()

A       AAL      AAPL      ABBV      ABNB       ABT      ACGL  \
0 -0.004186 -0.002602  0.001649  0.012173  0.005675  0.005444 -0.008260   
1  0.020711  0.010435  0.007821  0.020353 -0.008839 -0.001934 -0.011699   
2 -0.005541 -0.016351 -0.007097  0.018919  0.008369  0.010075  0.004013   
3  0.001205  0.006124  0.012392  0.005042 -0.002313  0.031745  0.004896   
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

        ACN      ADBE       ADI  ...       WTW        WY      WYNN       XEL  \
0  0.022359  0.021297 -0.002854  ...  0.000549 -0.008078 -0.020967  0.013567   
1  0.010276  0.016571  0.021896  ... -0.006152 -0.000679  0.004735 -0.015527   
2  0.002474  0.005112  0.007341  ...  0.003588  0.010526 -0.009426 -0.006164   
3 -0.011449  0.015934 -0.011120  ...  0.003811 -0.013441  0.007137 -0.001459   
4  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   

        XOM       XYL       YUM       ZBH      ZBRA       ZTS  
0 -0.015553 -0.010894  0.015861  0.002829 -0.015798 -0.002843  
1  0.003994  0.018745 -0.007136 -0.007052  0.015622  0.022923  
2  0.007514 -0.020047  0.002135  0.006481 -0.000033  0.005460  
3 -0.010705  0.003288 -0.006107 -0.000265 -0.021659  0.000792  
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  

[5 rows x 501 columns]

In [24]:
df_prices_pct.columns.name = None

In [25]:
df_volume = df_volume.drop('Unnamed: 0', axis = 1)

In [26]:
df_volume.head()

A         AAL        AAPL       ABBV       ABNB        ABT  \
0  3114800.0  52899000.0  50080500.0  4467800.0  3843400.0  4915100.0   
1  2893700.0  39161500.0  47471400.0  4215500.0  3048500.0  3880400.0   
2  2707500.0  34340900.0  54156800.0  5100500.0  3121500.0  3302300.0   
3  2269600.0  35840600.0  41181800.0  5186700.0  3463100.0  9835500.0   
4  2365300.0  29411400.0  53103900.0  3781700.0  2595600.0  8666600.0   

        ACGL        ACN       ADBE        ADI  ...       WTW         WY  \
0  1747000.0  3596600.0  3967700.0  3087800.0  ...  370300.0  2974200.0   
1  1217600.0  3498600.0  3183600.0  2616000.0  ...  259000.0  2485500.0   
2  1480100.0  3002200.0  3295000.0  4016700.0  ...  296100.0  2472400.0   
3  1132800.0  2363200.0  3235000.0  2757000.0  ...  255600.0  4555100.0   
4   803500.0  2626900.0  2684200.0  2208200.0  ...  319100.0  3397900.0   

        WYNN        XEL         XOM        XYL        YUM        ZBH  \
0  1197200.0  3195100.0  19589300.0  2466300.0  1618100.0  1662800.0   
1  1522900.0  3460000.0  19412200.0  1078400.0  2125200.0  1186700.0   
2  1335000.0  2474900.0  14863500.0   973500.0  1944000.0   918100.0   
3  1194600.0  2395000.0  13154100.0  1190300.0  1528900.0   902300.0   
4  1416200.0  3824500.0  13289200.0   873900.0  1467100.0  1070300.0   

       ZBRA        ZTS  
0  305600.0  2142700.0  
1  219500.0  1304400.0  
2  248000.0  1870800.0  
3  162800.0  2722200.0  
4  187300.0  1819400.0  

[5 rows x 501 columns]

In [27]:
df_volume['A'].dtype

dtype('float64')

In [28]:
df_volume.columns.name = None

In [29]:
df_volume.head()

A         AAL        AAPL       ABBV       ABNB        ABT  \
0  3114800.0  52899000.0  50080500.0  4467800.0  3843400.0  4915100.0   
1  2893700.0  39161500.0  47471400.0  4215500.0  3048500.0  3880400.0   
2  2707500.0  34340900.0  54156800.0  5100500.0  3121500.0  3302300.0   
3  2269600.0  35840600.0  41181800.0  5186700.0  3463100.0  9835500.0   
4  2365300.0  29411400.0  53103900.0  3781700.0  2595600.0  8666600.0   

        ACGL        ACN       ADBE        ADI  ...       WTW         WY  \
0  1747000.0  3596600.0  3967700.0  3087800.0  ...  370300.0  2974200.0   
1  1217600.0  3498600.0  3183600.0  2616000.0  ...  259000.0  2485500.0   
2  1480100.0  3002200.0  3295000.0  4016700.0  ...  296100.0  2472400.0   
3  1132800.0  2363200.0  3235000.0  2757000.0  ...  255600.0  4555100.0   
4   803500.0  2626900.0  2684200.0  2208200.0  ...  319100.0  3397900.0   

        WYNN        XEL         XOM        XYL        YUM        ZBH  \
0  1197200.0  3195100.0  19589300.0  2466300.0  1618100.0  1662800.0   
1  1522900.0  3460000.0  19412200.0  1078400.0  2125200.0  1186700.0   
2  1335000.0  2474900.0  14863500.0   973500.0  1944000.0   918100.0   
3  1194600.0  2395000.0  13154100.0  1190300.0  1528900.0   902300.0   
4  1416200.0  3824500.0  13289200.0   873900.0  1467100.0  1070300.0   

       ZBRA        ZTS  
0  305600.0  2142700.0  
1  219500.0  1304400.0  
2  248000.0  1870800.0  
3  162800.0  2722200.0  
4  187300.0  1819400.0  

[5 rows x 501 columns]

In [30]:
numeric_df_prices_pct = df_prices_pct.select_dtypes(include=['number'])

prices_pct_array = numeric_df_prices_pct.values

In [34]:
print(prices_pct_array)

[[-4.18557293e-03 -2.60188497e-03  1.64928675e-03 ...  2.82885278e-03
  -1.57982505e-02 -2.84268327e-03]
 [ 2.07106699e-02  1.04347727e-02  7.82089822e-03 ... -7.05218237e-03
   1.56224565e-02  2.29229592e-02]
 [-5.54060343e-03 -1.63510828e-02 -7.09656563e-03 ...  6.48086701e-03
  -3.25520833e-05  5.46010651e-03]
 ...
 [ 2.73626179e-03  2.21366251e-02 -3.43789246e-03 ...  6.88934271e-03
   9.08644044e-03  3.28069389e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]


In [31]:
numeric_df_volume = df_volume.select_dtypes(include = ['number'])

volume_array = numeric_df_volume.values

In [32]:
print(volume_array)

[[ 3114800. 52899000. 50080500. ...  1662800.   305600.  2142700.]
 [ 2893700. 39161500. 47471400. ...  1186700.   219500.  1304400.]
 [ 2707500. 34340900. 54156800. ...   918100.   248000.  1870800.]
 ...
 [ 1089900. 20533800. 38052200. ...   687000.   211200.  1485400.]
 [ 1577400. 22240100. 51906300. ...   801500.   319200.  1359900.]
 [ 1570700. 26521400. 52990800. ...  1584900.   453500.  2328500.]]


In [35]:
df_prices_pct.dtypes

A       float64
AAL     float64
AAPL    float64
ABBV    float64
ABNB    float64
         ...   
XYL     float64
YUM     float64
ZBH     float64
ZBRA    float64
ZTS     float64
Length: 501, dtype: object

In [33]:
# Turning data into a set of points
data = list(zip(df_prices_pct, df_volume))

linkage_data = linkage(data, method='average')

dendrogram(linkage_data)
plt.show()

ValueError: could not convert string to float: 'A'